require("mason").setup()
require("mason-lspconfig").setup()
vim.lsp.enable('clangd')
vim.lsp.config('clangd', {filetypes = { "c", "cpp", "objc", "objcpp", "cuda" }})
-- vim.lsp.enable('basedpyright')
-- vim.lsp.config('basedpyright', {settings = { basedpyright = { analysis = { typeCheckingMode = "standard", }, }, },})
vim.lsp.enable('ruff')
vim.lsp.enable('ty')
vim.lsp.enable('terraformls')
vim.lsp.enable('tflint')
vim.lsp.enable('yamlls')
vim.lsp.enable('jsonls')
vim.lsp.enable('protols')
vim.lsp.enable('jdtls')
-- For C#, using omnisharp-extended plugin instead
-- vim.lsp.enable('csharp_ls')
vim.lsp.enable('omnisharp')
vim.lsp.enable('slangd')

vim.keymap.set({"n"}, "gh", ":LspClangdSwitchSourceHeader<CR>")
vim.keymap.set({"i"}, "<c-k>", "<c-x><c-o>")
vim.keymap.set({"n"}, "<s-k>", vim.lsp.semantic_tokens.force_refresh)
vim.keymap.set({"n"}, "ml", vim.diagnostic.open_float)
vim.keymap.set({"n"}, "ql", vim.lsp.buf.signature_help)
vim.keymap.set({"n"}, "qh", vim.lsp.buf.hover)
vim.keymap.set("n", "<F2>", vim.lsp.buf.rename)
